# ASP.NET Core (.NET Framework)
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - '*'
    exclude:
      - main

pool:
  name: Default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
  - job: 'Build_Backend'
    displayName: 'Build .net core app'
    steps:
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '>=5.8.0'

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: --configuration $(buildConfiguration)

    - task: DotNetCoreCLI@2
      displayName: 'Run UnitTests'
      inputs:
       command: 'test'
       projects: '**/RoosterPlanner.*.csproj'
       arguments: '--collect "Code coverage" --logger trx'
       publishTestResults: true

  - job: 'ARM_Resource'
    displayName: 'Validate ARM'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Sponsorship - Roosterplanner - Dev'
        subscriptionId: 'cc4e763b-c3fc-4e33-9b20-bada439c8771'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'roosterplanner-rg-dev'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.sourcesDirectory)/RoosterPlanner.AzureResources/WebSiteSQLDatabase.json'
        csmParametersFile: '$(Build.sourcesDirectory)/RoosterPlanner.AzureResources/WebSiteSQLDatabase.parameters.json'
        deploymentMode: 'Validation'
        deploymentOutputs: 'outputs'
