import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TextInjectorService {
  public static level:string[]=['A1','A2','B1','B2','Moedertaal']
  public static countries:string[]=['Afghanistan',
    'Albanië',
    'Algerije',
    'Amerikaanse Maagdeneilanden',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua en Barbuda',
    'Argentinië',
    'Armenië',
    'Aruba',
    'Australië',
    'Azerbeidzjan',
    'Bahama\'s',
    'Bahrein',
    'Bangladesh',
    'Barbados',
    'België',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnië en Herzegovina',
    'Botswana',
    'Brazilië',
    'Britse Maagdeneilanden',
    'Brunei',
    'Bulgarije',
    'Burkina Faso',
    'Burundi',
    'Cambodja',
    'Canada',
    'Centraal-Afrikaanse Republiek',
    'Chili',
    'China',
    'Colombia',
    'Comoren',
    'Congo-Brazzaville',
    'Congo-Kinshasa',
    'Cookeilanden',
    'Costa Rica',
    'Cuba',
    'Curacao',
    'Cyprus',
    'Denemarken',
    'Djibouti',
    'Dominica',
    'Dominicaanse Republiek',
    'Duitsland',
    'Ecuador',
    'Egypte',
    'El Salvador',
    'Engeland',
    'Equatoriaal Guinea',
    'Eritrea',
    'Estland',
    'Ethiopië',
    'Faeröer',
    'Fiji',
    'Filipijnen',
    'Finland',
    'Frankrijk',
    'Frans Polynesië',
    'Gabon',
    'Gambia',
    'Georgië',
    'Ghana',
    'Gibraltar',
    'Grenada',
    'Griekenland',
    'Groenland',
    'Guam',
    'Guatamala',
    'Guernsey',
    'Guinee',
    'Guinee-Bissau',
    'Guyana',
    'Haïti',
    'Honduras',
    'Hong Kong',
    'Hongarije',
    'Ierland',
    'IJsland',
    'India',
    'Indonesië',
    'Irak',
    'Iran',
    'Israël',
    'Italië',
    'Ivoorkust',
    'Jamaica',
    'Japan',
    'Jemen',
    'Jersey',
    'Jordanië',
    'Kaaimaneilanden',
    'Kaapverdië',
    'Kameroen',
    'Kazachstan',
    'Kenia',
    'Kirgizië',
    'Kiribati',
    'Koeweit',
    'Kosovo',
    'Kroatië',
    'Laos',
    'Lesotho',
    'Letland',
    'Libanon',
    'Liberia',
    'Libië',
    'Liechtenstein',
    'Litouwen',
    'Luxemburg',
    'Macau',
    'Macedonië',
    'Madagaskar',
    'Malawi',
    'Malediven',
    'Maleisië',
    'Mali',
    'Malta',
    'Man',
    'Marokko',
    'Marshalleilanden',
    'Mauritanië',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldavië',
    'Monaco',
    'Mongolië',
    'Montenegro',
    'Montserrat',
    'Mozambique',
    'Myanmar',
    'Namibië',
    'Nauru',
    'Nederland',
    'Nepal',
    'Nicaragua',
    'Nieuw-Zeeland',
    'Niger',
    'Nigeria',
    'Niue',
    'Noord-Ierland',
    'Noord-Korea',
    'Noordelijke Marianen',
    'Noorwegen',
    'Oeganda',
    'Oekraïne',
    'Oezbekistan',
    'Oman',
    'Oostenrijk',
    'Oost-Timor',
    'Pakistan',
    'Palau',
    'Panama',
    'Papoea-Nieuw-Guinea',
    'Paraguay',
    'Peru',
    'Polen',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Roemenië',
    'Rusland',
    'Rwanda',
    'Saint Kitts en Nevis',
    'Saint Lucia',
    'Saint Vincent en de Grenadines',
    'Salomonseilanden',
    'Samoa',
    'San Marino',
    'Sao Tomé en Principe',
    'Saoedi-Arabië',
    'Schotland',
    'Senegal',
    'Servië',
    'Seychellen',
    'Sierra Leone',
    'Singapore',
    'Sint Maarten',
    'Slovenië',
    'Slowakije',
    'Soedan',
    'Somalië',
    'Spanje',
    'Sri Lanka',
    'Suriname',
    'Swaziland',
    'Syrië',
    'Tadzjikistan',
    'Taiwan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad en Tobago',
    'Tsjaad',
    'Tsjechië',
    'Tunesië',
    'Turkije',
    'Turkmenistan',
    'Turks en Caicoseilanden',
    'Tuvalu',
    'Uruguay',
    'Vanuatu',
    'Vaticaanstad',
    'Venezuela',
    'Verenigd Koninkrijk',
    'Verenigde Arabische Emiraten',
    'Verenigde Staten van Amerika',
    'Vietnam',
    'Wales',
    'Wit-Rusland',
    'Zambia',
    'Zimbabwe',
    'Zuid-Afrika',
    'Zuid-Korea',
    'Zweden',
    'Zwitserland',
  ];
  public static acceptedImageExtentions:string[]=['png','jpg','jpeg','gif','jfif','pjp','pjpeg']
  public static calenderSelectionOptions: string[] = ['Elke dag', 'Elke maandag', 'Elke dinsdag', 'Elke woensdag', 'Elke donderdag', 'Elke vrijdag', 'Elke zaterdag', 'Elke zondag', 'Verwijder selectie'];
  public static shiftTableColumnNames: string[] = ['Taak', 'Datum', 'Vanaf', 'Tot', '#Benodigde vrijwilligers'];
  public static availabilitiesTableColumnNames: string[] = ['Datum', 'Taak', 'Vanaf', 'Tot','Details'];
  public static scheduleTableColumnNames: string[] = ['Naam','Taak', 'Vanaf', 'Tot'];
  public static planShiftTableColumnNames: string[] = ['select', 'Naam', 'Leeftijd', 'Nationaliteit', '#Ingeroosterd', 'Ingeroosterd', 'Inzetbaarheid'];
  public static employeeTableColumnNames: string[] = ['Naam', 'Leeftijd', 'Nationaliteit'];
  public static nationalitiesDutch: string[] = [
    "Afghaans",
    "Afrika",
    "Albanees",
    "Algerijns",
    "Amerikaans",
    "Andorrees",
    "Angolees",
    "Argentijns",
    "Armeens",
    "Australisch",
    "Azerbeidzjaans",
    "Bahamaans",
    "Bahreins",
    "Barbadaans",
    "Belgisch",
    "Belizaans",
    "Bengalees",
    "Benins",
    "Bhutaans",
    "Boliviaans",
    "Bosnisch",
    "Botswaans",
    "Braziliaans",
    "Brits",
    "Bruneis",
    "Bulgaars",
    "Burger Antigua en Barbuda",
    "Burger Dominica",
    "Burger Marshalleilanden",
    "Burger Montenegro",
    "Burger Papoea-Nieuw-guinea",
    "Burger Saint Kitts en Nevis",
    "Burger Sao Tomé en Principe",
    "Burger Servië",
    "Burger Servië en Montenegro",
    "Burger Sint Vincent en de Grenadines",
    "Burger Timor Leste",
    "Burger Trinidad en Tobago",
    "Burger Verenigde Arabische Emiraten",
    "Burkinees",
    "Burundisch",
    "Cambodjaans",
    "Canadees",
    "Centraal-Afrikaans",
    "Chileens",
    "Chinees",
    "Colombiaans",
    "Comorees",
    "Congolees",
    "Costa",
    "Ricaans",
    "Cubaans",
    "Cyprisch",
    "Deens",
    "Djiboutiaans",
    "Dominicaans",
    "Duits",
    "Ecuadoraans",
    "Egyptisch",
    "Equatoriaal-Guinees",
    "Eritrees",
    "Ests",
    "Ethiopisch",
    "Fijisch",
    "Filippijns",
    "Fins",
    "Frans",
    "Gabonees",
    "Gambiaans",
    "Georgisch",
    "Ghanees",
    "Grenadaans",
    "Grieks",
    "Guatemalteeks",
    "Guinee-Bissaus",
    "Guinees",
    "Guyaans",
    "Haïtiaans",
    "Hondurees",
    "Hongaars",
    "Iers",
    "IJslands",
    "Indiaas",
    "Indonesisch",
    "Iraaks",
    "Iraans",
    "Israëlisch",
    "Italiaans",
    "Ivoriaans",
    "Jamaicaans",
    "Japans",
    "Jemenitisch",
    "Joegoslavisch",
    "Jordaans",
    "Kaapverdisch",
    "Kameroens",
    "Katarees",
    "Kazaks",
    "Keniaans",
    "Kiribatisch",
    "Koeweits",
    "Kosovaars",
    "Kroatisch",
    "Kyrgizisch",
    "Laotiaans",
    "Lesothaans",
    "Lets",
    "Libanees",
    "Liberiaans",
    "Libisch",
    "Liechtensteins",
    "Litouws",
    "Luxemburgs",
    "Macedonisch",
    "Madagaskisch",
    "Malawisch",
    "Maledivisch",
    "Maleisisch",
    "Malinees",
    "Maltees",
    "Marokkaans",
    "Mauritaans",
    "Mauritiaans",
    "Mexicaans",
    "Moldavisch",
    "Monegaskisch",
    "Mongools",
    "Mozambikaans",
    "Myanmarees",
    "Namibisch",
    "Nauruaans",
    "Nederlands",
    "Nepalees",
    "Nicaraguaans",
    "Nieuw-Zeelands",
    "Nigerees",
    "Nigeriaans",
    "Noord-Koreaans",
    "Noors",
    "Oceanië",
    "Oekraïens",
    "Oezbeeks",
    "Omanitisch",
    "Onbekend",
    "Oostenrijks",
    "Pakistaans",
    "Panamees",
    "Paraguayaans",
    "Peruaans",
    "Pools",
    "Portugees",
    "Roemeens",
    "Russisch",
    "Rwandees",
    "Salomonseilands",
    "Salvadoraans",
    "Samoaans",
    "San",
    "Marinees",
    "Saoedi-Arabisch",
    "Senegalees",
    "Seychels",
    "Sierra",
    "Leoons",
    "Singaporees",
    "Sint",
    "Luciaans",
    "Sloveens",
    "Slowaaks",
    "Soedanees",
    "Somalisch",
    "Sovjet-Russisch",
    "Spaans",
    "Sri",
    "Lankaans",
    "Surinaams",
    "Swazisch",
    "Syrisch",
    "Tadzjikistaans",
    "Taiwanees",
    "Tanzaniaans",
    "Thais",
    "Togolees",
    "Tongaans",
    "Tsjadisch",
    "Tsjechisch",
    "Tsjechoslowaaks",
    "Tunesisch",
    "Turkmeens",
    "Turks",
    "Tuvaluaans",
    "Ugandees",
    "Uruguayaans",
    "Vanuatuaans",
    "Vaticaans",
    "Venezolaans",
    "Vietnamees",
    "Wit-Russisch",
    "Zambiaans",
    "Zimbabwaans",
    "Zuid-Afrikaans",
    "Zuid-Koreaans",
    "Zuidsoedanese",
    "Zweeds",
    "Zwitsers",
  ];
  public static colors: string[] = ["Red", "Blue", "Yellow", "Green", "Orange", "Pink"];

  constructor() {
  }

 static getColor(color: string) {
    const colors: any = {
      red: {
        primary: '#ad2121',
        secondary: '#FAE3E3',
      },
      blue: {
        primary: '#1e90ff',
        secondary: '#D1E8FF',
      },
      yellow: {
        primary: '#e3bc08',
        secondary: '#FDF1BA',
      },
      green: {
        primary: '#1f931f',
        secondary: '#c0f2c0'
      },
      orange: {
        primary: '#cc5200',
        secondary: '#ffc299'
      },
      pink: {
        primary: '#cc0052',
        secondary: '#ffb3d1'
      }
    };

    switch (color.toLowerCase()) {
      case "red":
        return colors.red
      case "blue":
        return colors.blue
      case "yellow":
        return colors.yellow
      case "green":
        return colors.green
      case "orange":
        return colors.orange
      case "pink":
        return colors.pink
    }
  }
}
