import {Injectable} from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TextInjectorService {
  public static calenderSelectionOptions: string[] = ['Elke dag', 'Elke maandag', 'Elke dinsdag', 'Elke woensdag', 'Elke donderdag', 'Elke vrijdag', 'Elke zaterdag', 'Elke zondag', 'Verwijder selectie'];
  public static shiftTableColumnNames: string[] = ['Taak', 'Datum', 'Vanaf', 'Tot', '#Benodigde vrijwilligers'];
  public static planShiftTableColumnNames: string[] = ['select', 'Naam', 'Leeftijd', 'Nationaliteit', '#Ingeroosterd', 'Ingeroosterd', 'Inzetbaarheid'];
  public static nationalitiesDutch: string[] = [
    "Afghaans",
    "Afrika",
    "Albanees",
    "Algerijns",
    "Amerikaans",
    "Andorrees",
    "Angolees",
    "Argentijns",
    "Armeens",
    "Australisch",
    "Azerbeidzjaans",
    "Bahamaans",
    "Bahreins",
    "Barbadaans",
    "Belgisch",
    "Belizaans",
    "Bengalees",
    "Benins",
    "Bhutaans",
    "Boliviaans",
    "Bosnisch",
    "Botswaans",
    "Braziliaans",
    "Brits",
    "Bruneis",
    "Bulgaars",
    "Burger Antigua en Barbuda",
    "Burger Dominica",
    "Burger Marshalleilanden",
    "Burger Montenegro",
    "Burger Papoea-Nieuw-guinea",
    "Burger Saint Kitts en Nevis",
    "Burger Sao Tomé en Principe",
    "Burger Servië",
    "Burger Servië en Montenegro",
    "Burger Sint Vincent en de Grenadines",
    "Burger Timor Leste",
    "Burger Trinidad en Tobago",
    "Burger Verenigde Arabische Emiraten",
    "Burkinees",
    "Burundisch",
    "Cambodjaans",
    "Canadees",
    "Centraal-Afrikaans",
    "Chileens",
    "Chinees",
    "Colombiaans",
    "Comorees",
    "Congolees",
    "Costa",
    "Ricaans",
    "Cubaans",
    "Cyprisch",
    "Deens",
    "Djiboutiaans",
    "Dominicaans",
    "Duits",
    "Ecuadoraans",
    "Egyptisch",
    "Equatoriaal-Guinees",
    "Eritrees",
    "Ests",
    "Ethiopisch",
    "Fijisch",
    "Filippijns",
    "Fins",
    "Frans",
    "Gabonees",
    "Gambiaans",
    "Georgisch",
    "Ghanees",
    "Grenadaans",
    "Grieks",
    "Guatemalteeks",
    "Guinee-Bissaus",
    "Guinees",
    "Guyaans",
    "Haïtiaans",
    "Hondurees",
    "Hongaars",
    "Iers",
    "IJslands",
    "Indiaas",
    "Indonesisch",
    "Iraaks",
    "Iraans",
    "Israëlisch",
    "Italiaans",
    "Ivoriaans",
    "Jamaicaans",
    "Japans",
    "Jemenitisch",
    "Joegoslavisch",
    "Jordaans",
    "Kaapverdisch",
    "Kameroens",
    "Katarees",
    "Kazaks",
    "Keniaans",
    "Kiribatisch",
    "Koeweits",
    "Kosovaars",
    "Kroatisch",
    "Kyrgizisch",
    "Laotiaans",
    "Lesothaans",
    "Lets",
    "Libanees",
    "Liberiaans",
    "Libisch",
    "Liechtensteins",
    "Litouws",
    "Luxemburgs",
    "Macedonisch",
    "Madagaskisch",
    "Malawisch",
    "Maledivisch",
    "Maleisisch",
    "Malinees",
    "Maltees",
    "Marokkaans",
    "Mauritaans",
    "Mauritiaans",
    "Mexicaans",
    "Moldavisch",
    "Monegaskisch",
    "Mongools",
    "Mozambikaans",
    "Myanmarees",
    "Namibisch",
    "Nauruaans",
    "Nederlands",
    "Nepalees",
    "Nicaraguaans",
    "Nieuw-Zeelands",
    "Nigerees",
    "Nigeriaans",
    "Noord-Koreaans",
    "Noors",
    "Oceanië",
    "Oekraïens",
    "Oezbeeks",
    "Omanitisch",
    "Onbekend",
    "Oostenrijks",
    "Pakistaans",
    "Panamees",
    "Paraguayaans",
    "Peruaans",
    "Pools",
    "Portugees",
    "Roemeens",
    "Russisch",
    "Rwandees",
    "Salomonseilands",
    "Salvadoraans",
    "Samoaans",
    "San",
    "Marinees",
    "Saoedi-Arabisch",
    "Senegalees",
    "Seychels",
    "Sierra",
    "Leoons",
    "Singaporees",
    "Sint",
    "Luciaans",
    "Sloveens",
    "Slowaaks",
    "Soedanees",
    "Somalisch",
    "Sovjet-Russisch",
    "Spaans",
    "Sri",
    "Lankaans",
    "Surinaams",
    "Swazisch",
    "Syrisch",
    "Tadzjikistaans",
    "Taiwanees",
    "Tanzaniaans",
    "Thais",
    "Togolees",
    "Tongaans",
    "Tsjadisch",
    "Tsjechisch",
    "Tsjechoslowaaks",
    "Tunesisch",
    "Turkmeens",
    "Turks",
    "Tuvaluaans",
    "Ugandees",
    "Uruguayaans",
    "Vanuatuaans",
    "Vaticaans",
    "Venezolaans",
    "Vietnamees",
    "Wit-Russisch",
    "Zambiaans",
    "Zimbabwaans",
    "Zuid-Afrikaans",
    "Zuid-Koreaans",
    "Zuidsoedanese",
    "Zweeds",
    "Zwitsers",
  ];

  constructor() {
  }
}
