name: Build and publish

on:
  push:
    branches: [ refactor-ui ]

env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '3.1.x'
  AZURE_WEBAPP_PACKAGE_PATH: './RoosterPlanner.UI/'
  AZURE_WEBAPP_NAME: 'RoosterPlanner.UI'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET core
        uses: actions/setup-dotnet@v1
        with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.3
          run: |
            npm install
            npm run build --if-present
            npm run test --if-present


      #- name: build
        #run restore build publish


        #Resource groepen aanmaken mbv ps

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/src
          
      #api project



        


  

