name: Deploy

on:
  workflow_run:
    workflows: ["Build the project"]
    types:
      - completed
    
jobs:
  deployProd:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Run ARM deploy to Prd 
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG_PROD }} 
          template: ./RoosterPlanner.AzureResources/template.json
          parameters:
            environment=prd 
      
      #Download artifacts
      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: Build.yml
          name: "Web"
          path: ./staging/web

      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: Build.yml
          name: "Api"
          path: ./staging/api
      
      #Deploy
      - name: Deploy Web
        run: az webapp deployment source config-zip --src ./staging/web/web.zip --resource-group ${{ secrets.AZURE_RG_PROD }} --name roosterplanner-web-prd 
        shell: pwsh    
        
      - name: Deploy Api
        run: az webapp deployment source config-zip --src ./staging/api/api.zip --resource-group ${{ secrets.AZURE_RG_PROD }} --name roosterplanner-api-prd 
        shell: pwsh    


  deployDev:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Run ARM deploy to dev
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG_DEV }} 
          template: ./RoosterPlanner.AzureResources/template.json
          parameters:
            environment=dev

      #Download artifacts
      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: BuildForDeploy.yml
          name: "Web"

      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: BuildForDeploy.yml
          name: "Api"

      #Deploy
      - name: Deploy Web
        run: az webapp deployment source config-zip --src ./staging/web/web.zip --resource-group ${{ secrets.AZURE_RG_DEV }} --name roosterplanner-web-dev
        shell: pwsh

      - name: Deploy Api
        run: az webapp deployment source config-zip --src ./staging/api/api.zip --resource-group ${{ secrets.AZURE_RG_DEV }} --name roosterplanner-api-dev
        shell: pwsh