name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: roosterplanner-web-dev
  AZURE_API_NAME: roosterplanner-api-dev

  #Todo: Create resource groups and resources
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
 
      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: Build.yml
          name: "Web Artifact"
          path: ./staging/web
          
      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: Build.yml
          name: "Api Artifact"
          path: ./staging/api
                
      - name: publish front-end
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: ./staging/web/

      - name: publish api
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_API_NAME }}
          publish-profile: ${{ secrets.AZURE_API_PUBLISH_PROFILE  }}
          package: ./staging/api