name: Deploy Master

on:
  workflow_run:
    workflows: ["Build the project"]
    branches:
      - main
    types:
      - completed
    
jobs:
  deployProd:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Run ARM deploy to Prd 
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG_PROD }} 
          template: ./RoosterPlanner.AzureResources/template.json
          parameters:
            environment=prd
            firewallRuleDN=${{ secrets.ARM_FIREWALL_DN_IP }}
            firewallRuleOther=${{ secrets.ARM_FIREWALL_OTHER_IP }}
      
      #Download artifacts
      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: BuildForDeploy.yml
          name: "Web"

      - uses: dawidd6/action-download-artifact@v2.8.0
        with:
          workflow: BuildForDeploy.yml
          name: "Api"
      
      #Deploy
      - name: Deploy Web
        run: az webapp deployment source config-zip --src web.zip --resource-group ${{ secrets.AZURE_RG_PROD }} --name roosterplanner-web-prd 
        shell: pwsh    
        
      - name: Deploy Api
        run: az webapp deployment source config-zip --src api.zip --resource-group ${{ secrets.AZURE_RG_PROD }} --name roosterplanner-api-prd 
        shell: pwsh    
