name: Shared Infrastructure

on:
  push:
    branches:
      - main #["main", "develop"]#
      - feature/bicep
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  validate-bicep:
    name: Validate Bicep
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}

      - name: Validate Bicep
        uses: azure/bicep-deploy@v1
        # this gives an error but the deployment is on resource scope so we can't pass location
        with:
          name: "shared-bicep-validation"
          scope: resourceGroup
          type: deployment
          operation: validate
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME }}
          template-file: ./.infra/shared/main.bicep
          parameters-file: ./.infra/shared/main.dev.bicepparam

      - uses: actions/upload-artifact@v4
        with:
          name: shared-infra
          path: ./.infra/shared/

  deploy-dev:
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: shared-dev
    needs:
      - validate-bicep

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shared-infra
          path: ./.infra/shared/

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          enable-AzPSSession: true

      - name: Deploy Infra
        uses: azure/bicep-deploy@v1
        # this gives an error but the deployment is on resource scope so we can't pass location
        with:
          name: "dev-shared-deploy"
          scope: resourceGroup
          type: deployment
          operation: create
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME }}
          template-file: ./.infra/shared/main.bicep
          parameters-file: ./.infra/shared/main.dev.bicepparam

  deploy-prd:
    if: github.event_name != 'pull_request' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: shared-prd
    needs:
      - validate-bicep
      - deploy-dev

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: shared-infra
          path: ./.infra/shared/

      - name: Log in with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          enable-AzPSSession: true

      - name: Deploy Infra
        uses: azure/bicep-deploy@v1
        # this gives an error but the deployment is on resource scope so we can't pass location
        with:
          name: "prd-shared-deploy"
          scope: resourceGroup
          type: deployment
          operation: create
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          resource-group-name: ${{ secrets.AZURE_RG_NAME }}
          template-file: ./.infra/shared/main.bicep
          parameters-file: ./.infra/shared/main.prd.bicepparam
